const CONFIG={name:"kamu",birthday:"2026-10-22T00:00:00+07:00",letter:["Hari ini, aku langitkan semua doa baik untuk kamu.","Semoga hal-hal yang membuatmu lelah perlahan berubah menjadi alasan untuk tersenyum.","Semoga langkahmu dimudahkan, rezekimu dilapangkan, dan orang-orang baik selalu menemukan jalan menuju hidupmu.","Dan semoga kamu selalu punya alasan untuk bangga pada dirimu sendiri."]};
(function(){const p=new URLSearchParams(location.search);if(p.get("to"))CONFIG.name=p.get("to");if(/^\d{4}-\d{2}-\d{2}$/.test(p.get("date")||""))CONFIG.birthday=p.get("date")+"T00:00:00+07:00";})();
const $=s=>document.querySelector(s);
const screens={intro:$("#intro"),letter:$("#letter"),wish:$("#wish"),gift:$("#gift"),nope:$("#nope"),candle:$("#candle"),flower:$("#flower-screen"),final:$("#final")};
const ORDER=["intro","letter","wish","gift","candle","flower","final"];
const music=$("#background-music");
$("#nameIntro").textContent=CONFIG.name;$("#nameFinal").textContent=CONFIG.name;document.title=`For ${CONFIG.name} ♡`;
let current="intro",noTries=2,giftOpened=false,finished=false,sfxOn=true,micStream=null,audioCtx=null,analyser=null,blowTimer=null,sfxCtx=null;
function progress(name){const i=ORDER.indexOf(name);document.querySelectorAll("#progress i").forEach(d=>{const n=ORDER.indexOf(d.dataset.step);d.classList.toggle("on",n===i);d.classList.toggle("done",n>=0&&n<i);});}
function showScreen(name){if(!screens[name])return;Object.values(screens).forEach(s=>s.classList.remove("active"));screens[name].classList.add("active");current=name;progress(name);if(name==="flower"){const b=$("#bouquetScene");b.classList.remove("bloom-in");void b.offsetWidth;b.classList.add("bloom-in");}}
function typeWriter(lines){const el=$("#typeText");el.textContent="";let a=0,b=0;function tick(){if(a>=lines.length)return;const line=lines[a];if(b<line.length){el.textContent+=line[b++];setTimeout(tick,24)}else{el.textContent+="\n\n";a++;b=0;setTimeout(tick,320)}}tick();}
function startMusic(){music.play().catch(()=>{});}function getSfx(){if(!sfxCtx)sfxCtx=new(window.AudioContext||window.webkitAudioContext)();return sfxCtx;}
function sfx(type){if(!sfxOn)return;try{const c=getSfx(),o=c.createOscillator(),g=c.createGain(),p={tap:[520,640,.09,"sine"],pop:[300,900,.22,"triangle"],whoosh:[180,60,.35,"sawtooth"],chime:[660,990,.5,"sine"]}[type]||[520,640,.09,"sine"],t=c.currentTime;o.type=p[3];o.frequency.setValueAtTime(p[0],t);o.frequency.exponentialRampToValueAtTime(Math.max(1,p[1]),t+p[2]);g.gain.setValueAtTime(.05,t);g.gain.exponentialRampToValueAtTime(.0001,t+p[2]);o.connect(g);g.connect(c.destination);o.start();o.stop(t+p[2]+.02)}catch(e){}}
function confetti(count=150){const layer=$("#confetti"),colors=["#ff8db6","#ffb8d1","#a28cff","#fff","#ffd166"];for(let i=0;i<count;i++){const e=document.createElement("i");e.className="confetti";e.style.left=Math.random()*100+"vw";e.style.setProperty("--x",Math.random()*320-160+"px");e.style.animationDelay=Math.random()*.5+"s";e.style.background=colors[(Math.random()*colors.length)|0];layer.appendChild(e);setTimeout(()=>e.remove(),4200)}}
function goGift(){giftOpened=false;$("#giftTitle").innerHTML="Ada <em>hadiah</em> buat kamu.";$("#giftQuestion").innerHTML="Tapi sebelum itu...<br><strong>kamu mau?</strong>";$("#choiceHint").textContent="sentuh hadiahnya dulu ✦";showScreen("gift");}
function goCandle(){finished=false;$("#cakeScene").classList.remove("blown");$("#micStatus").textContent="izin mikrofon opsional · tap api selalu bisa";showScreen("candle");}
function finishCandle(){if(finished)return;finished=true;stopMic();$("#cakeScene").classList.add("blown");$("#micStatus").textContent="wish made ✦";confetti(45);setTimeout(()=>{sfx("chime");showScreen("flower")},900)}
function goFinal(){showScreen("final");confetti(180);}
$("#openBtn").onclick=()=>{sfx("pop");startMusic();showScreen("letter");typeWriter(CONFIG.letter)};
$("#nextBtn").onclick=()=>{sfx("tap");showScreen("wish")};$("#giftBtn").onclick=()=>{sfx("tap");goGift()};$("#closeBtn").onclick=()=>showScreen("intro");
$("#againBtn").onclick=()=>{noTries=2;document.body.classList.remove("celebrating");showScreen("intro")};
$("#musicBtn").onclick=()=>{if(music.paused){startMusic();$("#musicBtn").textContent="♫"}else{music.pause();$("#musicBtn").textContent="Ⅱ"}};
$("#sfxBtn").onclick=()=>{sfxOn=!sfxOn;$("#sfxBtn").textContent=sfxOn?"🔔":"🔕";if(sfxOn)sfx("tap")};
$("#giftObject").onclick=()=>{const b=$("#giftObject");if(giftOpened){b.animate([{transform:"scale(1)"},{transform:"scale(.95)"},{transform:"scale(1)"}],{duration:220});return}giftOpened=true;sfx("whoosh");b.classList.add("shaking");setTimeout(()=>{b.classList.remove("shaking");sfx("pop");confetti(25);$("#giftTitle").innerHTML="Nah... <em>ini buat kamu.</em>";$("#giftQuestion").innerHTML="Sekarang pilih dengan jujur.<br><strong>mau atau nggak?</strong>";$("#choiceHint").textContent="aku lihat pilihanmu 👀"},450)};
$("#yesBtn").onclick=()=>{sfx("chime");goCandle()};
$("#noBtn").onclick=()=>{sfx("tap");noTries--;$("#noCount").textContent="kesempatan: "+Math.max(noTries,0);if(noTries<=0){$("#nopeTitle").innerHTML="Masih <em>ga mau?</em> 😛";$("#nopeText").innerHTML="Oke... aku tawarin lagi. Jangan nyesel ya."}showScreen("nope")};
$("#retryBtn").onclick=()=>goGift();
$("#reallyNoBtn").onclick=()=>{$("#nopeTitle").innerHTML="Yakin banget? <em>😳</em>";$("#nopeText").innerHTML="Yaudah... aku tunggu. Tapi hadiahnya masih di sini 😛";$("#reallyNoBtn").textContent="oke, aku mau ❤️";$("#reallyNoBtn").onclick=()=>goGift()};
$("#flameTarget").onclick=()=>{sfx("whoosh");finishCandle()};$("#tapFlameBtn").onclick=()=>{sfx("whoosh");finishCandle()};$("#flowerNextBtn").onclick=()=>{sfx("tap");goFinal()};
async function startMic(){if(finished)return;if(!navigator.mediaDevices?.getUserMedia){$("#micStatus").textContent="mikrofon tidak tersedia · tap api saja ✦";return}try{micStream=await navigator.mediaDevices.getUserMedia({audio:true});audioCtx=new(window.AudioContext||window.webkitAudioContext)();analyser=audioCtx.createAnalyser();analyser.fftSize=512;analyser.connect(audioCtx.destination);const src=audioCtx.createMediaStreamSource(micStream);src.connect(analyser);const data=new Uint8Array(analyser.fftSize);let strong=0;$("#micStatus").textContent="tiup ke mikrofon... 🎙️";blowTimer=setInterval(()=>{analyser.getByteTimeDomainData(data);let sum=0;for(const v of data){const n=(v-128)/128;sum+=n*n}const rms=Math.sqrt(sum/data.length);strong=rms>.07?strong+1:Math.max(0,strong-1);if(strong>4)finishCandle()},50)}catch(e){$("#micStatus").textContent="mikrofon dilewati · tap api saja ✦"}}
function stopMic(){if(blowTimer){clearInterval(blowTimer);blowTimer=null}if(micStream){micStream.getTracks().forEach(t=>t.stop());micStream=null}if(audioCtx){audioCtx.close().catch(()=>{});audioCtx=null;analyser=null}}
$("#blowBtn").onclick=startMic;
function spawnHeart(){const layer=$("#hearts"),e=document.createElement("span");e.className="floating-heart";e.textContent=Math.random()>.5?"♡":"♥";e.style.left=Math.random()*100+"vw";e.style.fontSize=12+Math.random()*20+"px";e.style.setProperty("--drift",Math.random()*140-70+"px");layer.appendChild(e);setTimeout(()=>e.remove(),10500)}setInterval(spawnHeart,1600);for(let i=0;i<4;i++)setTimeout(spawnHeart,i*400);
if(matchMedia("(hover:hover) and (pointer:fine)").matches){const glow=$("#cursorGlow");addEventListener("pointermove",e=>{glow.style.transform=`translate(${e.clientX-130}px,${e.clientY-130}px)`;glow.classList.add("visible")});}
document.addEventListener("keydown",e=>{if(["ArrowRight","Enter"," "].includes(e.key)){if(current==="intro")$("#openBtn").click();else if(current==="letter")$("#nextBtn").click();else if(current==="wish")$("#giftBtn").click();else if(current==="flower")$("#flowerNextBtn").click()}if(e.key==="Escape"&&current!=="intro")showScreen("intro")});
let sx=0;document.addEventListener("touchstart",e=>sx=e.changedTouches[0].clientX,{passive:true});document.addEventListener("touchend",e=>{const dx=e.changedTouches[0].clientX-sx;if(dx<-70){if(current==="letter")$("#nextBtn").click();else if(current==="wish")$("#giftBtn").click();else if(current==="flower")$("#flowerNextBtn").click()}},{passive:true});
progress("intro");
